### ISSUE TITLE
Custom token replacement

### ISSUE THREAD

**Issue by dquser** [chucknorris/roundhouse#220] opened 2015-10-14 15:05 UTC
Our team need custom token replacement (in addition to the current configuration token replacement). Our idea is to pass these replacements in a querystring-like way (e.g. /Tokens=Key1=Value1&Key2=Value2) or in a similar way. We wouldn't want to hardcore the tokens in the source code.
I'm wondering if you ever considered this feature and if we could contribute to the project with this feature. Thank You.

**Comment by dquser** [comment] 2015-10-14 18:46
Actually, if we choose a prefix for the custom tokens (such as @), it would be pretty easy to pass custom parameters and update the code accordingly: /@Key1=Value /@Key2=Value2

**Comment by ferventcoder** [comment] 2015-10-14 21:05
This is a duplicate I believe.

**Comment by ferventcoder** [comment] 2015-10-14 21:07
Yes it is - closing as duplicate of #140, and there is a PR that the user needs to fix up at #166.

**Closed by ferventcoder** 2015-10-14 21:07 UTC
